### ISSUE TITLE
Compilation error on PHP 7 env

### ISSUE THREAD

**Issue by Spomky** [bukka/php-crypto#11]
Hi,

I have the following error when I try to install this library on PHP 7 env:

```sh
/tmp/pear/temp/crypto/crypto_alg.c:24:40: fatal error: ext/standard/php_smart_str.h: No such file or directory
```
See https://travis-ci.org/Spomky-Labs/jose/jobs/79110993

Any idea to fix this?

**Comment by bukka** [comment]
crypto_alg.c is in 0.1.0 that doesn't support 7. You need to either use master branch or wait for 0.2.0 that should come in the next few months.

**Comment by Spomky** [comment]
Great! Thank you.
I tried using the master branch, but I have [errors too](https://travis-ci.org/Spomky-Labs/jose/jobs/79113140):

```sh
/home/travis/build/Spomky-Labs/jose/php-crypto/php_crypto.h:106: multiple definition of `php_crypto_long_to_int'
.libs/crypto.o:/home/travis/build/Spomky-Labs/jose/php-crypto/php_crypto.h:106: first defined here
```

**Comment by bukka** [comment]
Looks like a bug. I'll take a look later into it...

**Comment by bukka** [comment]
It should be fixed now. Let me know if there is any other issue.

**Comment by Spomky** [comment]
Compilation succeeded. Thanks
