### ISSUE TITLE
phpc directory is empty in git

### ISSUE THREAD

**Issue by remicollet** [bukka/php-crypto#12]
so trying to build from git clone fails:

     /work/GIT/php-crypto/php_crypto.h:48:23: fatal error: phpc/phpc.h: No such file or directory

File is present in pecl archive.

**Comment by bukka** [comment]
Have you used `--recursive` when cloning the repo as documented in

https://github.com/bukka/php-crypto#manual-installation

phpc is a submodule...

**Comment by remicollet** [comment]
Sorry, I have miss the submodule...
