### ISSUE TITLE
'STREAM_ASSUME_REALPATH' undeclared

### ISSUE THREAD

**Issue by dbadia** [bukka/php-crypto#14]
Hi -
Trying to compile from source, but make results in the following error:

`/bin/sh /home1/thebadia/tmp/php-crypto/libtool --mode=compile cc  -I. -I/home1/thebadia/tmp/php-crypto -DPHP_ATOM_INC -I/home1/thebadia/tmp/php-crypto/include -I/home1/thebadia/tmp/php-crypto/main -I/home1/thebadia/tmp/php-crypto -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home1/thebadia/tmp/php-crypto/crypto_stream.c -o crypto_stream.lo
libtool: compile:  cc -I. -I/home1/thebadia/tmp/php-crypto -DPHP_ATOM_INC -I/home1/thebadia/tmp/php-crypto/include -I/home1/thebadia/tmp/php-crypto/main -I/home1/thebadia/tmp/php-crypto -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home1/thebadia/tmp/php-crypto/crypto_stream.c  -fPIC -DPIC -o .libs/crypto_stream.o
/home1/thebadia/tmp/php-crypto/crypto_stream.c: In function 'php_crypto_stream_opener':
/home1/thebadia/tmp/php-crypto/crypto_stream.c:532: error: 'STREAM_ASSUME_REALPATH' undeclared (first use in this function)
/home1/thebadia/tmp/php-crypto/crypto_stream.c:532: error: (Each undeclared identifier is reported only once
/home1/thebadia/tmp/php-crypto/crypto_stream.c:532: error: for each function it appears in.)
make: *** [crypto_stream.lo] Error 1`

Perhaps I am missing some dependency.  Full output from phpize, configure, and make is attached

[crypto.txt](https://github.com/bukka/php-crypto/files/83430/crypto.txt)

**Comment by bukka** [comment]
It looks to me like you are trying to compile it on 5.2 (I see API version 20041225) which is not supported. Only 5.3+ is supported mainly due to namespaces...

**Comment by bukka** [comment]
I just updated README.md with info about a minimal version of PHP and OpenSSL. I noticed that it wasn't documented. Thanks.
