### ISSUE TITLE
Question: authentication only

### ISSUE THREAD

**Issue by Spomky** [bukka/php-crypto#18]
Hi,

I am not sure this is the right place ask my question, but it seems that you contribute to the GCM mode implementation on PHP 7.1 and you may help me.

My question is how to use authentication only with the OpenSSL method on PHP 7.1?

With this extension it works fine:

```php
<?php
use Crypto\Cipher;

$cipher = Cipher::aes(Cipher::MODE_GCM, $key_length);
$cipher->setAAD($A);
$cipher->setTagLength($tag_length);
$ciphertext = $cipher->encrypt(null, $key, $iv);
$tag = $cipher->getTag();
```

The `$ciphertext ` is `null` as expected and the decryption does not return any error.

But with the OpenSSL method, the ciphertext is not null:

```php
<?php

$tag = null;
$ciphertext = openssl_encrypt(null, $mode, $key, OPENSSL_RAW_DATA, $iv, $tag, $aad, $tag_length);
```

Do you have any idea?

**Comment by bukka** [comment]
Sorry for the late answer: should be because of this: https://bugs.php.net/bug.php?id=74099

It should be fixed by https://github.com/php/php-src/pull/2389
