### ISSUE TITLE
RAND_pseudo_bytes() is deprecated since OpenSSL 1.1.0

### ISSUE THREAD

**Issue by dktapps** [bukka/php-crypto#30]
It's only used [here](https://github.com/bukka/php-crypto/blob/master/crypto_rand.c#L153).

Its recommended replacement is `RAND_bytes`, which is already used in the other branch.
I'm not sure if we can just ditch the branch entirely or not. I noted that ext-openssl uses `BCryptGenRandom` on Windows instead of `RAND_bytes` (https://github.com/php/php-src/blame/4b79dba93202ed5640dff317046ce2fdd42e1d82/ext/openssl/openssl.c#L7368, https://github.com/php/php-src/blob/1e0610fe243fcfafd23ff821129cf4f35148ac64/win32/winutil.c#L118)

**Comment by bukka** [comment]
Yeah we should just ditch the whole branch. `BCryptGenRandom` was added in past where there were some issues with OpenSSL rand on Win but that's no longer the case. So it's not needed here.

**Comment by dktapps** [comment]
What about older PHP versions / older OpenSSL?
